[project]
name = "3-simple-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastapi[standard]>=0.115.13",
  "uvicorn"
]

[project.optional-dependencies]
dev = []

[tool.setuptools]
packages = ["mathUtils"]
